# Generated by Django 5.0.6 on 2024-06-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_category", models.CharField(max_length=255)),
                ("explanation", models.TextField()),
                ("feedback", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_number", models.CharField(max_length=255)),
                ("application_date", models.DateField()),
                ("publication_number", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                ("cpc", models.JSONField()),
                ("ipc", models.JSONField()),
                ("claim", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Lipstick",
        ),
        migrations.AddField(
            model_name="classificationresult",
            name="patent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.patent"
            ),
        ),
    ]
